[paths]

# these can be relative to this file
games = "/mnt/me/games/Steam/steamapps/common/"
application_data = "./.numidium"
mods = "./mods"
modlists = "./modlists"

[games.skyrim32]
# custom path can be defined if they are not in the default game directory
# can also be relative to the default directory
path = "/mnt/me/moregames/Steam/steamapps/common/Skyrim"
